version: '3.1'
services: 
  nginx:
    restart: always 
    image: daocloud.io/library/nginx:1.15.9
    container_name: nginx 
    ports:
      - 8000:80
    volumes:
      - /opt/nginx/conf.d/:/etc/nginx/conf.d/
